schemaVersion: "2.0.0"

metadataTest:
  workdir: "/home/devops"
  entrypoint: ["/bin/bash", "--init-file", "/home/devops/.bashrc-ni"]

commandTests:
  - name: "terraform installation"
    command: "terraform"
    args: ["--help"]
    expectedOutput: ["Usage: terraform.*"]

  - name: "Kubectl CLI installation"
    command: "kubectl"
    args: ["version", "--client"]
    expectedOutput: [".*v1.15.5.*"]

  - name: "git installation"
    command: "git"
    args: ["--help"]
    expectedOutput: ["usage: git.*"]

  - name: "curl installation"
    command: "curl"
    args: ["--help"]
    expectedOutput: ["Usage: curl.*"]

  - name: "unzip installation"
    command: "unzip"
    args: ["--help"]
    expectedOutput: ["UnZip.*"]

  - name: "bash installation"
    command: "bash"
    args: ["--help"]
    expectedOutput: ["GNU bash.*"]

fileExistenceTests:
  - name: 'jenkins-config-template.xml'
    path: '/home/devops/etc'
    shouldExist: true

  - name: "terraform-provider-ibm.*"
    path: "/home/devops/.terraform.d/plugins"
    shouldExist: true
