name: Docker build

# Controls when the workflow will run
on:
  release:
    types:
      - published
  pull_request:
    branches:
      - main
  label:
    types:
      - created
      - edited
      - deleted

jobs:
  check_labels:
    name: Check labels
    runs-on: ubuntu-latest
    steps:
      - uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          one_of: major,minor,patch
          any_of: bug,enhancement,chore
          repo_token: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'label' }}

    strategy:
      matrix:
        base:
          - alpine
          - fedora
        terraform:
          - 1.6.3
          - 1.7.7
          - 1.8.7
          - 1.9.0

    env:
      TERRAFORM_LATEST: "1.9.0"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Login to CNTK Quay
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_CNTK_USERNAME }}
          password: ${{ secrets.QUAY_CNTK_TOKEN }}

      - name: Setup variables ${{ matrix.base }}:${{ matrix.terraform }}
        id: variables
        shell: bash
        run: |
          SHORT_TERRAFORM=$(echo ${{ matrix.terraform }} | sed -E "s/([0-9]+[.][0-9]+)[.][0-9]+/\1/g")
          
          SHORT_TAG_ENABLED="false"
          if [[ "${{ matrix.base }}" == "alpine" ]]; then
            SHORT_TAG_ENABLED="true"
          fi
          
          BASE_ENABLED="false"
          LATEST_ENABLED="false"
          if [[ "${SHORT_TERRAFORM}" == "${TERRAFORM_LATEST}" ]]; then
            BASE_ENABLED="true"
            
            if [[ "${{ matrix.base }}" == "alpine" ]]; then
              LATEST_ENABLED="true"
            fi
          fi
          
          RELEASE_TAG=${GITHUB_REF#refs/tags/}
          RELEASE_TAG_ENABLED="false"
          RELEASE_TAG_SHORT_ENABLED="false"
          if [[ "${GITHUB_REF}" =~ refs/tags ]] && [[ "${RELEASE_TAG}" != "main" ]]; then
            RELEASE_TAG_ENABLED="true"
          
            if [[ "${{ matrix.base }}" == "alpine" ]]; then
              RELEASE_TAG_SHORT_ENABLED="true"
            fi
          else
            RELEASE_TAG="main"
          fi
          
          echo "Short terraform: ${SHORT_TERRAFORM}"
          echo "terraform=$SHORT_TERRAFORM" >> $GITHUB_OUTPUT
          
          echo "Short tag enabled: $SHORT_TAG_ENABLED"
          echo "short-enabled=$SHORT_TAG_ENABLED" >> $GITHUB_OUTPUT
          
          echo "Release tag: ${RELEASE_TAG}"
          echo "release-tag=$RELEASE_TAG" >> $GITHUB_OUTPUT
          
          echo "Release tag enabled: $RELEASE_TAG_ENABLED"
          echo "release-tag-enabled=$RELEASE_TAG_ENABLED" >> $GITHUB_OUTPUT
          
          echo "Release tag short enabled: $RELEASE_TAG_SHORT_ENABLED"
          echo "release-tag-short-enabled=$RELEASE_TAG_SHORT_ENABLED" >> $GITHUB_OUTPUT
          
          echo "Base enabled: $BASE_ENABLED"
          echo "base-enabled=$BASE_ENABLED" >> $GITHUB_OUTPUT
          
          echo "Latest enabled: $LATEST_ENABLED"
          echo "latest-enabled=$LATEST_ENABLED" >> $GITHUB_OUTPUT

      - name: Docker CNTK meta ${{ matrix.base }}:${{ matrix.terraform }}
        id: cntk-meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            quay.io/cloudnativetoolkit/terraform
          # Docker tags based on the following events/attributes
          tags: |
            type=raw,value=v${{ steps.variables.outputs.terraform }}-${{ matrix.base }}
            type=raw,value=v${{ steps.variables.outputs.terraform }},enable=${{ steps.variables.outputs.short-enabled }}
            type=raw,value=v${{ steps.variables.outputs.terraform }}-${{ steps.variables.outputs.release-tag }}-${{ matrix.base }},enable=${{ steps.variables.outputs.release-tag-enabled }}
            type=raw,value=v${{ steps.variables.outputs.terraform }}-${{ steps.variables.outputs.release-tag }},enable=${{ steps.variables.outputs.release-tag-short-enabled }}
            type=raw,value=${{ matrix.base }},enable=${{ steps.variables.outputs.base-enabled }}
            type=raw,value=latest,enable=${{ steps.variables.outputs.latest-enabled }}

      - name: Build and push ${{ matrix.base }}:${{ matrix.terraform }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Containerfile-${{ matrix.base }}
          build-args: |
            TERRAFORM_VERSION=${{ matrix.terraform }}
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.cntk-meta.outputs.tags }}
          labels: ${{ steps.cntk-meta.outputs.labels }}

  verify:
    needs: ["build", "check_labels"]
    runs-on: ubuntu-latest

    steps:
      - name: Verify
        run: |
          echo "Success"

  notify:
    needs: ["build"]
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}

    strategy:
      matrix:
        repo:
          - cloud-native-toolkit/image-github-terraform-runner
          - cloud-native-toolkit/image-cli-tools-core

    steps:
      - name: Repository dispatch ${{ matrix.repo }}
        uses: cloud-native-toolkit/action-repository-dispatch@main
        with:
          notifyRepo: ${{ matrix.repo }}
          eventType: released
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
