name: Docker build

# Controls when the workflow will run
on:
  push:
    branches:
      - 'v*.*'
  release:
    types:
      - published
  pull_request:
    branches:
      - 'v*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Login to CNTK Quay
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_CNTK_USERNAME }}
          password: ${{ secrets.QUAY_CNTK_TOKEN }}

      - name: Docker CNTK meta
        id: cntk-meta
        uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          images: |
            quay.io/cloudnativetoolkit/terraform
          # Docker tags based on the following events/attributes
          tags: |
            type=match,pattern=v(.*),group=1
            type=ref,event=branch
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.cntk-meta.outputs.tags }}
          labels: ${{ steps.cntk-meta.outputs.labels }}
